# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Game On! Adventures with microservices
description: > # this means to ignore newlines until "baseurl:"
  Hands-on experiment building microservices and cloud native applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-90113653-2


# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-mentions
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
